# $schema: https://raw.githubusercontent.com/cloudogu/gitops-playground/main/docs/configuration.schema.json
content:
  repos:
    - url: https://github.com/cloudogu/gitops-build-lib
      target: 3rd-party-dependencies/gitops-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/ces-build-lib
      target: 3rd-party-dependencies/ces-build-lib
      overwriteMode: RESET
    - url: https://github.com/cloudogu/spring-petclinic
      target: tenant1/petclinic-plain
      ref: feature/gitops_ready
      targetRef: main
      #      ref: b0738b2
      overwriteMode: UPGRADE
      createJenkinsJob: true
    - url: 'https://github.com/cloudogu/gop-multi-tenant-shared-example'
      path: repos
      ref: main
      templating: true
      type: FOLDER_BASED
      overwriteMode: UPGRADE

  namespaces:
    - ${config.application.namePrefix}tenant1-production
    - ${config.application.namePrefix}tenant1-staging
    - ${config.application.namePrefix}tenant2

application:
  yes: true
  baseUrl: http://localhost
jenkins:
  active: true
registry:
  active: true
features:
  argocd:
    active: true
  ingressNginx:
    active: true